-- Smiling Monad administrator control centre data.
-- This migration adds account moderation and app-usage reporting only.
-- It does not change Kimi, the Companion gateway, tool selection or execution.

create table if not exists public.app_usage_events (
  id bigint generated by default as identity primary key,

  user_id uuid
    references auth.users(id)
    on delete set null,

  event_name text not null,
  area text not null default 'general',
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null
    default now()
);

create index if not exists
  app_usage_events_user_id_idx
on public.app_usage_events(user_id);

create index if not exists
  app_usage_events_created_at_idx
on public.app_usage_events(created_at desc);

create index if not exists
  app_usage_events_area_idx
on public.app_usage_events(area);

alter table public.app_usage_events
enable row level security;

drop policy if exists
  "Authenticated users can record their own usage"
  on public.app_usage_events;

create policy
  "Authenticated users can record their own usage"
on public.app_usage_events
for insert
to authenticated
with check (
  user_id = auth.uid()
);

drop policy if exists
  "Administrators can read all usage"
  on public.app_usage_events;

create policy
  "Administrators can read all usage"
on public.app_usage_events
for select
to authenticated
using (
  public.is_smiling_monad_admin()
);

create or replace function public.sm_admin_usage_summary(
  days_back integer default 30
)
returns table (
  total_events bigint,
  active_users bigint,
  office_events bigint,
  community_events bigint,
  training_events bigint,
  wellbeing_events bigint,
  circle_events bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*)::bigint as total_events,
    count(distinct user_id)::bigint as active_users,
    count(*) filter (
      where area = 'office'
    )::bigint as office_events,
    count(*) filter (
      where area = 'community'
    )::bigint as community_events,
    count(*) filter (
      where area = 'training'
    )::bigint as training_events,
    count(*) filter (
      where area = 'wellbeing'
    )::bigint as wellbeing_events,
    count(*) filter (
      where area = 'circle'
    )::bigint as circle_events
  from public.app_usage_events
  where created_at >=
    now() - make_interval(
      days => greatest(days_back, 1)
    )
    and public.is_smiling_monad_admin();
$$;

revoke all
on function public.sm_admin_usage_summary(integer)
from public;

grant execute
on function public.sm_admin_usage_summary(integer)
to authenticated;